//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaulStovell.TrialBalance.Website {
    
    public partial class Builds {
        protected System.Web.UI.WebControls.PlaceHolder _downloadAreaPlaceholder;
        protected System.Web.UI.WebControls.DataGrid _buildsDataGrid;
    }
}
