//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.112
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaulStovell.TrialBalance.MainWebsite.Administration {
    
    public partial class EditBuild {
        protected System.Web.UI.WebControls.CheckBox _successfulCheckBox;
        protected System.Web.UI.WebControls.CheckBox _stableCheckbox;
        protected System.Web.UI.WebControls.CheckBox _publicCheckbox;
    }
}
