//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.112
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaulStovell.TrialBalance.MainWebsite.Administration {
    
    public partial class EditScreenshot {
        protected System.Web.UI.WebControls.TextBox _captionTextBox;
        protected System.Web.UI.WebControls.FileUpload _imageFileUpload;
        protected System.Web.UI.WebControls.Button Button1;
        protected System.Web.UI.WebControls.Button Button2;
    }
}
